language: node_js
sudo: false
node_js:
  - "5.7.0"
notifications:
  email:
    - yelm-eng@microsoft.com
script:
    - make all
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi